baseURL: "/"
languageCode: "en-us"
title: "Davide's blog"
theme: "PaperMod"
googleAnalytics: "UA-111281648-1"

# [params]
#   description = ""
#   logo = "icons/logo.png"
#   themeColor = "theme-base-09"
params:
  homeInfoParams:
    Content: I write about tech, story, strategy, information & marketing. I also help companies [find their voice](https://davideberretta.com/). <br/><br> Get these posts via email [here](http://eepurl.com/cSDdRr)

  socialIcons:
    - name: instagram
      url: https://instagram.com/daveeday
    - name: linkedin
      url: https://linkedin.com/in/davideberretta
    - name: twitter
      url: https://twitter.com/daveeday
    - name: email
      url: mailto:david.e.berretta@gmail.com?subject=Hello
    - name: phone
      url: https://clarity.fm/davideb